version: '3'

output: 'prefixed'

tasks:

  format:
    cmds:
      - >
        poetry run autoflake
        --exclude '*.local*'
        --expand-star-imports
        --in-place
        --recursive
        --remove-all-unused-imports
        --remove-duplicate-keys
        --remove-unused-variables
        --verbose
        .
      - poetry run black .
      - poetry run isort .
    desc: "format code with autoflake, black, isort"

  run:
    cmds:
      - poetry run alembic upgrade head
      - poetry run uvicorn api.main:app --reload

  reload:
    cmds:
      - task: format
      - task: run

  sync:
    cmds:
      - task: source .venv/bin/activate
      - task: pip freeze > requirements.txt
      - task: run
