"""remove permissions from role

Revision ID: a14bc286fdb4
Revises: b69b0a194ef0
Create Date: 2023-12-16 16:51:59.908472

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a14bc286fdb4"
down_revision: Union[str, None] = "b69b0a194ef0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role", sa.Column("permissions", sqlite.JSON(), nullable=True)
    )
    # ### end Alembic commands ###
