"""just in case

Revision ID: 3a362ecb8ed8
Revises: a14bc286fdb4
Create Date: 2023-12-16 18:47:22.442183

"""
from typing import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "3a362ecb8ed8"
down_revision: Union[str, None] = "a14bc286fdb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
